version: 2
jobs:
  build:
    working_directory: ~/Fountain
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "versions.gradle" }}-{{ checksum  "fountain/build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "versions.gradle" }}-{{ checksum  "fountain/build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Project
          command: ./gradlew build
      - run:
          name: Run detektCheck
          command: ./gradlew detektCheck
      - run:
          name: Generate Coverage
          command: ./gradlew jacocoTestReportDebug
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: fountain/build/reports
          destination: reports/fountain
      - store_artifacts:
          path: app/build/reports
          destination: reports/app
  test_api_v16:
      working_directory: ~/Fountain
      docker:
          - image: circleci/android:api-26-alpha
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - run:
            name: Accept licenses
            command: yes | sdkmanager --licenses || true
        - run:
            name: Setup emulator
            command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
        - run:
            name: Change circle-android script file permissions
            command: sudo chmod +rx /bin/circle-android
        - run:
            name: Launch emulator
            command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
            background: true
        - run:
            name: Wait emulator
            command: |
              # wait for it to have booted
              circle-android wait-for-boot
              # unlock the emulator screen
              sleep 30
              adb shell input keyevent 82
        - run:
            name: Run Tests
            command: ./gradlew :fountain:connectedAndroidTest
        - store_artifacts:
            path: fountain/build/reports
            destination: reports
        - store_test_results:
            path: fountain/build/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_api_v16:
          requires:
            - build
